import { taskCard } from "@/components/pages/tasks/content/taskCards/taskCards";

export const InitialTasks: taskCard[] = [
  {
    id: 1,
    type: "full",
    status: "available",
    title: "Волшебный курсор",
    image: "card-1.png",
    activationDate: "active",
    target_task_href: "https://www.google.com/",
  },
  {
    id: 2,
    type: "short",
    status: "available",
    title: "Гирляндное настроение",
    image: "card-2.png",
    activationDate: "active",
    target_task_href: "https://www.google.com/",
  },
  {
    id: 3,
    type: "short",
    status: "available",
    title: "Праздничный рецепт",
    image: "card-3.png",
    activationDate: "active",
    target_task_href: "https://www.google.com/",
  },
  {
    id: 4,
    type: "short",
    status: "notAvailable",
    title: "Курс на Великий Устюг",
    image: "card-3.png",
    activationDate: "2024-12-15T00:00:00+03:00",
    target_task_href: "https://www.google.com/",
  },
  {
    id: 5,
    type: "short",
    status: "notAvailable",
    title: "Москва новогодняя",
    image: "card-3.png",
    activationDate: "2024-12-16T00:00:00+03:00",
    target_task_href: "https://www.google.com/",
  },
  {
    id: 6,
    type: "full",
    status: "notAvailable",
    title: "Мандаринка для друга",
    image: "card-6.png",
    activationDate: "2024-12-17T00:00:00+03:00",
    target_task_href: "https://www.google.com/",
  },
  {
    id: 7,
    type: "full",
    status: "notAvailable",
    title: "Новогодний кинотеатр",
    image: "card-6.png",
    activationDate: "2024-12-18T00:00:00+03:00",
    target_task_href: "https://www.google.com/",
  },
  {
    id: 8,
    type: "short",
    status: "notAvailable",
    title: "Прогулка по склонам",
    image: "card-3.png",
    activationDate: "2024-12-19T00:00:00+03:00",
    target_task_href: "https://www.google.com/",
  },
  {
    id: 9,
    type: "short",
    status: "notAvailable",
    title: "Новогодняя почта",
    image: "card-3.png",
    activationDate: "2024-12-20T00:00:00+03:00",
    target_task_href: "https://www.google.com/",
  },
  {
    id: 10,
    type: "short",
    status: "notAvailable",
    title: "Музыкальная пауза",
    image: "card-3.png",
    activationDate: "2024-12-21T00:00:00+03:00",
    target_task_href: "https://www.google.com/",
  },
  {
    id: 11,
    type: "short",
    status: "notAvailable",
    title: "Это точно ваш конёк!",
    image: "card-3.png",
    activationDate: "2024-12-22T00:00:00+03:00",
    target_task_href: "https://www.google.com/",
  },
  {
    id: 12,
    type: "full",
    status: "notAvailable",
    title: "Новогоднее путешествие",
    image: "card-6.png",
    activationDate: "2024-12-23T00:00:00+03:00",
    target_task_href: "https://www.google.com/",
  },
  {
    id: 13,
    type: "short",
    status: "notAvailable",
    title: "И вот она, нарядная!",
    image: "card-3.png",
    activationDate: "2024-12-24T00:00:00+03:00",
    target_task_href: "https://www.google.com/",
  },
  {
    id: 14,
    type: "short",
    status: "notAvailable",
    title: "Снегопад на карте",
    image: "card-3.png",
    activationDate: "2024-12-25T00:00:00+03:00",
    target_task_href: "https://www.google.com/",
  },
];
